### ISSUE TITLE
replicates in setp 5

### ISSUE THREAD

**Issue by alerubio** [sunnysun515/MapRRCon#1]
Hi, I am wondering if it is possible to use replicates in the step 5 to normalize the chipS
I have replicates as controls for each. Should I use only one of them?

Thanks and bests 

# MapRRCon step 5 - Normalization
# To normalize ChIP file against Input
# need the mapped reads file

# This function takes 5 varibles:
# 1) chip_file: name of the ChIP file
# 2) ctr_file: name of the INPUT/control file
# 3) mapped_chip: # of mapped reads in the ChIP file
# 4) mapped_control: # of mapped reads in the control file
# 5) l1family: name of the L1 family

**Comment by sunnyosun** [comment]
Hi, I would suggest running the chip-ctr replicate pairs through normalization independently. You may average them after the normalization.

Hope this helps,
~Sunny
